### PR TITLE
EDLP New Groundlayout and newly generated TopSky Maps 

### PR DESCRIPTION
**Pull request by sergej-singer**
EuroScope_0uFCIlrXEb
EuroScope_0Xz8A3ZD63

New GRP Map for EDLP created using Mapbuilder including:
+ New DFS Ground Layout
+ AoR
+ TORA & RRS
+ Closure of Taxiway E
+ New APP Window

**TopSky Maps were newly generated using Mapbuilder using the Source files!**
Source files are now located in `mapbuilder\data`. Mover.py is no longer needed! As I had to create entirely new Map and Stand files, I took all the original Maps and Stands that were located in the Source Folder and reorganized them for the Mapbuilder. The order of Maps and Stands was changed, but not the contents!

* Some GRP Settings were changed to accommodate new Maps
* EDLP Stands were updated
* All Source files (like .kml-Files), that were used to create new Maps, are also included in the Pull-Request
* This Pull-Request includes Mapbuilder itself, but it was slightly modified for some use-cases (Support for MultiGeometries and some Fixes)

### CODE REVIEW

**Comment by capzDE** [comment]
- AoRs are very clear at this airport, not sure the border is needed
- runway markings also seem unnecessary
- remove RRS markers, EDLP is not approved for RRS
- if possible, add EDLR and Büren airport symbols to APP window

I'll look a bit more closely into what's turned on by default and what not another time, but I think there are some things shown in the screenshots that should be turned off by default for similarity between the various ground ASRs

**Comment by sergej-singer** [comment]
> * AoRs are very clear at this airport, not sure the border is needed

Fair enough, but I would still leave the frequencies, as it's pretty helpful. This map is turned off by default.

> * runway markings also seem unnecessary

It's on by default, but as it's a separate map, it can be turned off.

> * remove RRS markers, EDLP is not approved for RRS

Could you please elaborate in which airports it's approved? (DM in Discord is fine)

> * if possible, add EDLR and Büren airport symbols to APP window

Alright.

> I'll look a bit more closely into what's turned on by default and what not another time, but I think there are some things shown in the screenshots that should be turned off by default for similarity between the various ground ASRs

For that screenshot all the maps were turned on, I guess I should have made multiple screenshots to show which ones are by default and which aren't. 

Here's the view with only default maps on:
image
image

**Comment by capzDE** [comment]
> Fair enough, but I would still leave the frequencies, as it's pretty helpful. This map is turned off by default.

I mean, it's not complicated and if in doubt there's still the station list and/or the quicksheet. But I get your point - if you leave the frequencies in, I would also leave the separating line in

> It's on by default, but as it's a separate map, it can be turned off.

Off as default would be better here to keep the same style in all ground ASRs

> Could you please elaborate in which airports it's approved? (DM in Discord is fine)

In EDGG, it's only EDDF, EDDK, EDDL, and EDDS to my knowledge (maybe EDDG as well?) - definitely not the non-DFS TWRs though.

> For that screenshot all the maps were turned on, I guess I should have made multiple screenshots to show which ones are by default and which aren't.
> Here's the view with only default maps on

Thanks, that's really helpful!
In my opinion, it would be better for the surrounding airspace (i.e. the TMZ in this case) around the CTR to also be shown by default in the APP window; this would again result in the same style across the different ground ASRs and is of course also helpful for situational awareness.
The TORA should be off by default just like in all other ASRs and it would also be nice to see the TORA for full length as well in that map.
Finally, I would use a TS map for the TWY (and perhaps also stand) labels where the corresponding map is off by default but hooked to the Alt+G shortcut that we have for this purpose at other airports; again, to keep the same style, and in this case particularly also so trainees learn the feature early on and know about it once they get to airports where the ground layout isn't as easy to memorize.

**Comment by sergej-singer** [comment]
I had plans to update actually all the ASRs and make old DFS layouts in the same manner as I made this one, so I could make it pretty standard across EDGG.

**Comment by sergej-singer** [comment]
and I find Runway Markings pretty helpful in case the runway is actually shorter than it is, this is Dortmund for example:
image

**Comment by sergej-singer** [comment]
> The TORA should be off by default just like in all other ASRs and it would also be nice to see the TORA for full length as well in that map.

hm, yeah, indeed. I will make them then for all holding points.

**Comment by capzDE** [comment]
> I had plans to update actually all the ASRs and make old DFS layouts in the same manner as I made this one, so I could make it pretty standard across EDGG.

We actually also have this on our ToDo list (#186 and #127), but I'm sure nobody would complain if you want to do this 😄
Probably best if you get in contact with @LeoKle about it, though, as he is working on the mapbuilder stuff already.

> and I find Runway Markings pretty helpful in case the runway is actually shorter than it is

Nothing speaks against having it available as an option, but from all German airports where I have seen the RW ground radar (and mind you, most don't actually have one), they are not shown - it is something that controllers can customize, but from what I understand, nobody has it displayed by default to reduce unnecessary clutter. Airports with a (significant) displaced threshold would rather have a white line at the runway threshold perpendicular to the runway axis; you can see an example of this in the EDDS_DFS_GND.asr.
Additionally, we also need to keep in mind that it will not be possible to create all airports' ground ASRs with the mapbuilder as the underlying data is simply not available for all airports (for military airports it appears to be missing in general - although I'm not sure if this also applies to military airports with shared civilian use and for civilian airports we had identified the data for EDDG and EDFM to be missing) - in order to still maintain a reasonable similarity between all ASRs we should limit the amount of operationally unnecessary (or at least rarely necessary) data on the ASRs.
Thinking of this, I would also say that we should remove the roads from default view and make them an optional item for controllers instead. We could also think about removing the background thingy entirely - it is not part of our existing *DFS_GND.asr files and the RW ground radars also don't make a distinction here.

> hm, yeah, indeed. I will make them then for all holding points. But I would leave them on by default, because other FIRs do that as well. (Speaking of München for example)

While I can't speak for the general custom in EDDM (or EDMM in general), the TORA is not something I have seen displayed in any RW ground radar that I've seen. In my opinion, it's also rather superfluous to have it shown as pilots will have the information in their charts, so there is essentially never a need for ATC specifically to know the exact values.

**Comment by LeoKle** [comment]
We are already in contact.
As communicated, we will have to check if and how we have to replace our mover workflow.
That will take time as we will have to migrate the data.

**Comment by sergej-singer** [comment]
I just tried to implement Labels for Taxiways and Stands into Topsky. Turns out GRP draws its maps on top of the Topsky. So I guess it won't be possible :/

**Comment by sergej-singer** [comment]
I'm closing this Pull Request, as the EDLP Layout is already added to the 2407 and migration to the Map Builder is now on TODO list.

**Pull request closed without merging**
